site:
  title: Couchbase Docs
  url: https://docs.couchbase.com
  start_page: home::index.adoc
  keys:
    google_analytics: GTM-MVPNN2
content:
  branches: release/*
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: https://github.com/couchbase/couchbase-operator.git
    branches: [1.2.x, 1.1.x, 1.0.x]
    start_path: docs/user
  - url: https://github.com/couchbase/couchbase-elasticsearch-connector.git
    branches: [master, release/4.1, release/4.0, release/cypress]
    start_path: docs
  - url: https://github.com/couchbase/kafka-connect-couchbase.git
    branches: [master, release/3.3]
    start_path: docs
  - url: https://github.com/couchbase/couchbase-spark-connector.git
    branches: [master, release/2.3, release/2.2, release/2.1]
    start_path: docs
  - url: https://github.com/couchbase/docs-connectors-talend.git
    branches: master
  - url: https://github.com/couchbase/docs-analytics.git
    branches: [release/6.5, release/6.0, release/5.5]
  - url: https://github.com/couchbase/couchbase-cli.git
    branches: [master, alice, vulcan, spock, 5.0.1]
    start_path: docs
  - url: https://github.com/couchbase/backup.git
    branches: [mad-hatter, alice, vulcan, spock, 5.0.x]
    start_path: docs
  # NOTE server-docs is currently after other server repos so nav key wins
  - url: https://github.com/couchbase/docs-server.git
    branches: [mad-hatter, release/6.0, release/5.5, release/5.1, release/5.0, release/4.6, release/4.5, release/4.1, release/4.0]
  - url: https://github.com/couchbase/docs-sdk-common.git
  - url: https://github.com/couchbase/docs-sdk-c.git
  - url: https://github.com/couchbase/docs-sdk-dotnet.git
  - url: https://github.com/couchbase/docs-sdk-go.git
  - url: https://github.com/couchbase/docs-sdk-java.git
  - url: https://github.com/couchbase/docs-sdk-nodejs.git
  - url: https://github.com/couchbase/docs-sdk-php.git
  - url: https://github.com/couchbase/docs-sdk-python.git
  - url: https://github.com/couchbase/docs-sdk-scala.git
  - url: https://github.com/couchbaselabs/docs-couchbase-lite.git
    branches: [release/2.6, release/2.5, release/2.1, release/2.0, release/1.4, release/1.3]
  - url: https://github.com/couchbaselabs/docs-sync-gateway.git
    branches: [release/2.6, release/2.5, release/2.1, release/2.0, release/1.5, release/1.4, release/1.3]
  - url: https://github.com/couchbase-partners/test-drive-couchbase
    branches: [docs-site-pub]
  # Tutorial repositories
  - url: https://github.com/couchbaselabs/tutorials.git
    branches: master
  - url: https://github.com/couchbaselabs/tutorial-template.git
    branches: master
  - url: https://github.com/couchbaselabs/mobile-travel-sample.git
    branches: master
    start_path: content
  - url: https://github.com/couchbaselabs/hotel-finder-react-native.git
    branches: master
  - url: https://github.com/couchbaselabs/hotel-lister-cordova.git
    branches: master
  - url: https://github.com/couchbaselabs/tutorials-contrib.git
    branches: master
  - url: https://github.com/couchbaselabs/mobile-training-todo.git
    branches: tutorials
    start_path: content
  - url: https://github.com/couchbaselabs/UniversityLister-Android.git
    branches: master
    start_path: content
  - url: https://github.com/couchbaselabs/userprofile-couchbase-mobile.git
    branches: [standalone, query, sync, backgroundfetch]
    start_path: content
  - url: https://github.com/couchbaselabs/userprofile-couchbase-mobile-xamarin.git
    branches: [standalone, query, sync]
  - url: https://github.com/couchbaselabs/couchbase-lite-ios-api-playground.git
    branches: master
  - url: https://github.com/couchbaselabs/userprofile-couchbase-mobile-android.git
    branches: [standalone, query, sync]
asciidoc:
  attributes:
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    site-stage-production: ''
    tabs: tabs
    toc: ~
    xrefstyle: short
  extensions:
  - ./lib/json-config-ui-block-macro.js
  - ./lib/inline-man-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/tabs-block.js
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/v229/ui-bundle.zip
  supplemental_files:
  - path: robots.txt
    contents: |
      User-agent: *
  - path: ui.yml
    contents: |
      static_files: [robots.txt]
output:
  dir: ./public
