site:
  title: Couchbase Docs (Beta)
  url: https://docs.couchbase.com
  start_page: home::index.adoc
content:
  branches: [release/*, '!release/6.0']
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: git@github.com:couchbase/couchbase-operator.git
    branches: beta2
    start_path: docs/user
  - url: https://github.com/cb-docs-review-space/couchbase-elasticsearch-connector.git
    branches: release/cypress
    start_path: docs
  - url: https://github.com/cb-docs-review-space/kafka-connect-couchbase.git
    branches: release/3.3-patched
    start_path: docs
  - url: https://github.com/couchbase/couchbase-spark-connector.git
    branches: master
    start_path: docs
  - url: git@github.com:couchbase/docs-connectors-talend.git
    branches: master
  - url: git@github.com:couchbase/docs-analytics.git
  - url: https://github.com/cb-docs-review-space/couchbase-cli.git
    start_path: docs
  - url: git@github.com:cb-docs-review-space/backup.git
    start_path: docs
  # NOTE server-docs is currently after other server repos so nav key wins
  - url: git@github.com:couchbase/docs-server.git
  - url: git@github.com:couchbase/docs-sdk-c.git
  - url: git@github.com:couchbase/docs-sdk-dotnet.git
  - url: git@github.com:couchbase/docs-sdk-go.git
  - url: git@github.com:couchbase/docs-sdk-java.git
  - url: git@github.com:couchbase/docs-sdk-nodejs.git
  - url: git@github.com:couchbase/docs-sdk-php.git
  - url: git@github.com:couchbase/docs-sdk-python.git
asciidoc:
  attributes:
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    site-stage-production: ''
    tabs: tabs
    toc: ~
    xrefstyle: short
  extensions:
  - ./lib/json-config-ui-block-macro.js
  - ./lib/man-inline-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/tabs-block.js
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/v132/ui-bundle.zip
output:
  dir: ./public
