site:
  title: Couchbase Docs (Staging)
  url: https://docs-staging.couchbase.com
  start_page: home::index.adoc
content:
  branches: release/*
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: git@github.com:couchbase/couchbase-operator.git
    branches: master
    start_path: docs/user
  - url: https://github.com/couchbaselabs/couchbase-elasticsearch-connector.git
    branches: release/cypress
    start_path: docs
  - url: https://github.com/couchbase/kafka-connect-couchbase.git
    branches: [master, release/3.3]
    start_path: docs
  - url: https://github.com/couchbase/couchbase-spark-connector.git
    branches: [master, release/2.1]
    start_path: docs
  - url: git@github.com:couchbase/docs-connectors-talend.git
    branches: master
  - url: git@github.com:couchbase/docs-analytics.git
  - url: https://github.com/couchbase/couchbase-cli.git
    branches: [alice, vulcan, spock, 5.0.1]
    start_path: docs
  - url: git@github.com:couchbase/backup.git
    branches: [master, vulcan, spock, 5.0.x]
    start_path: docs
  # NOTE server-docs is currently after other server repos so nav key wins
  - url: https://github.com/couchbase/docs-server.git
  - url: git@github.com:couchbase/docs-sdk-common.git
  - url: git@github.com:couchbase/docs-sdk-c.git
  - url: git@github.com:couchbase/docs-sdk-dotnet.git
  - url: git@github.com:couchbase/docs-sdk-go.git
  - url: git@github.com:couchbase/docs-sdk-java.git
  - url: git@github.com:couchbase/docs-sdk-nodejs.git
  - url: git@github.com:couchbase/docs-sdk-php.git
  - url: git@github.com:couchbase/docs-sdk-python.git
  - url: https://github.com/couchbaselabs/docs-couchbase-lite.git
    branches: [master, release/2.0]
  - url: https://github.com/couchbaselabs/docs-sync-gateway.git
    branches: [master, release/2.0]
asciidoc:
  attributes:
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    toc: ~
    xrefstyle: short
  extensions:
  - ./lib/json-config-ui-block-macro.js
  - ./lib/man-inline-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/tabs-block.js
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/v168/ui-bundle.zip
  supplemental_files:
  - path: robots.txt
    contents: |
      User-agent: *
      Disallow: /
  - path: ui.yml
    contents: |
      static_files: [robots.txt]
output:
  dir: ./public
