services:
  kroki:
    image: yuzutech/kroki:latest
    depends_on:
      - blockdiag
      - mermaid
      - bpmn
      - excalidraw
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
    ports:
      - "9500:8000"
    restart: always
  blockdiag:
    image: yuzutech/kroki-blockdiag:latest
    expose:
      - "8001"
    restart: always
  mermaid:
    image: yuzutech/kroki-mermaid:latest
    expose:
      - "8002"
    restart: always
  bpmn:
    image: yuzutech/kroki-bpmn:latest
    expose:
      - "8003"
    restart: always
  excalidraw:
    image: yuzutech/kroki-excalidraw:latest
    expose:
      - "8004"
    restart: always
